language: node_js
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm install -g mocha
- npm install -g nyc
- npm install -g codeclimate-test-reporter
- npm install -g sequelize-cli
- npm run setup:test
after_script:
- npm run coverage
services:
- postgresql
node_js:
- node
- '6'
env:
  global:
  - URL_TEST=postgres://postgres@localhost/travis_ci_test
  - CXX=g++-4.8
  - NODE_ENV=test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
