export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_GROUP = 'ADD_GROUP';
export const CHANGE_GROUP = 'CHANGE_GROUP';
export const RECEIVE_GROUP = 'RECEIVE_GROUP';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_USER = 'ADD_USER';

export const REMOVE_USER_FROM_GROUP = 'REMOVE_USER_FROM_GROUP';

export const SAVE_USERNAME = 'SAVE_USERNAME';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_CHANNELS_FAIL = 'LOAD_CHANNELS_FAIL';

export const RECEIVE_USER = 'RECEIVE_USER';

export const LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
export const LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
export const LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';

export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

