export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CHANGE_GROUP = 'CHANGE_GROUP';
export const RECEIVE_GROUPS_SUCCESS = 'RECEIVE_GROUPS_SUCCESS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const LOAD_GROUPS = 'LOAD_GROUPS';
export const LOAD_GROUPS_FAIL = 'LOAD_GROUPS_FAIL';

export const GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS';
export const ADD_MESSAGE_TO_GROUP_SUCCESS = 'ADD_MESSAGE_TO_GROUP_SUCCESS';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_MEMBERS_SUCCESS = 'ADD_MEMBERS_SUCCESS';

export const REMOVE_USER_FROM_GROUP = 'REMOVE_USER_FROM_GROUP';

export const SAVE_USERNAME = 'SAVE_USERNAME';

export const RECEIVE_USER = 'RECEIVE_USER';
